server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: aa
    password: bb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      max-lifetime: 30000
      connection-timeout: 30000
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

app:
  allowed-origin: http://localhost:3000

logging:
  config: classpath:log4j2/log4j2.xml

casbin:
  enableCasbin: true
  useSyncedEnforcer: false
  useDistributedEnforcer: false
  autoSave: true
  storeType: jdbc
  tableName: tbl_casbin_rule
  initializeSchema: create
  model: classpath:casbin/model.conf
  useDefaultModelIfModelNotSetting: true
  enableWatcher: false