server:
  port: 8080
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: password
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "health,prometheus"

app:
  allowed-origin: http://localhost:3000

jwt:
  secret: secret-key
  access-token-expiration: 86400    # 24 hours
  refresh-token-expiration: 604800  # # 7 days
