server:
  port: 8080
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: "xxxx"
    password: "xxxx"
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: password
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "health,prometheus"

app:
  allowed-origin: http://localhost:3000

jwt:
  secret: secret-key
  access-token-expiration: 300000
  refresh-token-expiration: 600000
